### ISSUE TITLE
Difficult to look for oxygen beds

### ISSUE THREAD

**Issue by rutvijkarkhanis** [covidarmy/frontend#25] opened 2021-04-30 14:41 UTC
![Screenshot_2021-04-30-19-15-18-358_com whatsapp](https://user-images.githubusercontent.com/28397927/116711119-2c92de80-a9f0-11eb-9ca5-ac273f285bb0.png)

**Comment by nilshah98** [comment] 2021-04-30 17:20
Might be duplicate of #19

**Closed** 2021-05-06 17:11 UTC
